appvalidade/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
# Importa o módulo path
from django.urls import path

# import o arquivo de views
from . import views

app_name = 'main'

urlpatterns = [
    # path("produtos/", views.produto_list, name='lista_produtos'),
    # path("produtos/<slug:slug>/", views.produto_detalhes, name='detalhes_produtos'),
    # path('login/', views.login_pagina, name='login_pagina'),
    path('', views.index, name='index'),
    path("conferencias/", views.conferencia_list, name='lista_conferencia'),
    path("conferencias/<int:id>/", views.detalhes_conferencia, name='detalhes_conferencia'),    
    path("nova-conferencia/", views.nova_conferencia, name='nova_conferencia'),
    path("nova-conferencia-itens/", views.nova_conferecia_itens, name='nova_conferencia_itens'),    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse  # Importa o módulo responsável por retornar o url reverso


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class Filial(models.Model):
    # id automático
    nome = models.CharField(max_length=30)
    slug = models.SlugField(max_length=30, unique=True)

    class Meta:
        verbose_name_plural = 'Filiais'
        ordering = ['nome']

    def __str__(self):
        return str(self.nome)


class Funcionario(models.Model):
    # Chave estrangeira para o perfil, usando o model User default
    usuario = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    filial = models.ForeignKey(Filial, default=1, related_name='filial_funcionario', on_delete=models.CASCADE)
    cargo = models.CharField(max_length=20)
    #slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        ordering = ['usuario']

    def __str__(self):
        return str(self.usuario)


class Corredor(models.Model):
    # id automático
    nome = models.CharField(max_length=30)
    slug = models.SlugField(max_length=30, unique=True)
    descricao = models.CharField(max_length=50)
    filial = models.ForeignKey(Filial, default=1, related_name='filial_corredor', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Corredores'
        ordering = ['nome']

    def __str__(self):
        filial = str(self.filial)
        corredor = str(self.nome)
        return str(filial + ' - ' + corredor)


class Categoria(models.Model):
    # id automático
    descricao = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ['descricao']

    def __str__(self):
        return self.descricao


class Produto(models.Model):
    # id automático
    codigo = models.IntegerField(unique=True)
    codigo_barras = models.IntegerField(unique=True)
    descricao = models.CharField(max_length=255, unique=False)
    preco_venda = models.DecimalField(decimal_places=2, max_digits=6)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Produtos'

    def __str__(self):

        # Sempre que printar o id do objeto, irá retornar codigo_barras + descricao

        cod = str(self.codigo_barras)
        desc = self.descricao
        return str(cod + ' - ' + desc)

    def get_absolute_url(self):
        # app_name:nome_do_url, kwargs = {"campo_bd":"self.campo_bd"}
        return reverse("main:detalhes_produtos", kwargs={"slug": self.slug})


class Conferencia(models.Model):
    # id automático
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE)
    corredor = models.ForeignKey(Corredor, on_delete=models.CASCADE)
    data_conferencia = models.DateField(auto_now_add=True)

    def __str__(self):
        cod = str(self.id)
        data = str(self.data_conferencia)
        return str(cod + ' - ' + data)

    def get_absolute_url(self):
        return reverse("main:detalhes_conferencia", kwargs={"id": self.id})


class Validade_Produto(models.Model):
    # id automático
    conferencia = models.ForeignKey(Conferencia, on_delete=models.CASCADE, unique=False)
    codigo_barras = models.ForeignKey(Produto, on_delete=models.CASCADE, unique=False)
    data_validade = models.DateField(unique=False)
    quantidade = models.IntegerField()

    '''
    def get_absolute_url(self):
        return reverse("main/detalhes_conferencia", kwargs={"id": self.id})
    '''


class ConferenciaItens(TimeStampedModel):
    conferencia = models.ForeignKey(
        Conferencia,
        on_delete=models.CASCADE
    )
    produto = models.ForeignKey(
        Produto,
        on_delete=models.CASCADE
    )
    quantidade = models.PositiveSmallIntegerField()
    data_validade = models.DateField()

    class Meta:
        ordering = ('-created',)
        verbose_name = 'conferência item'
        verbose_name_plural = 'conferência itens'

    def __str__(self):
        return f'{self.produto}'

main/forms.py
# from django.forms import ModelForm
from .models import Conferencia, Validade_Produto

from django import forms

# Criação do formulário de conferência

class ConferenciaForm(forms.ModelForm):
    class Meta:
        model = Conferencia
        fields = ['corredor']

        # widgets = {'corredor': forms.TextInput}

class ValidadeProdutoForm(forms.ModelForm):
    class Meta:
        model = Validade_Produto
        # campo conferência vai ser preenchido usando o id da conferência criada
        fields = ['codigo_barras', 'data_validade', 'quantidade']
        widgets = {'codigo_barras': forms.TextInput}

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from django.urls import reverse

from django.core.exceptions import ValidationError

# from django.forms.models import inlineformset_factory

# DetailView -> Lista os detalhes
# ListView -> Lista os posts

# from django.views.generic import DetailView, ListView

from .models import Produto, Conferencia, Validade_Produto, Funcionario
from .filters import *
from .forms import ConferenciaForm, ValidadeProdutoForm

'''
class ProdutoListView(ListView):
    model = Produto
    
class ProdutoDetailView(DetailView):
    model = Produto

class ConferenciaListView(ListView):
    model = Conferencia

class ConferenciaDetailView(DetailView):
    model = Conferencia

class ValidadeProdutoListView(ListView):
    model = Validade_Produto

class ValidadeProdutoDetailView(DetailView):
    model = Validade_Produto
'''

'''
def produto_list(request):
    produtos = Produto.objects.all().order_by('codigo') # Pega todos os produtos
    return render(request, 'main/produto_list.html', {'produtos': produtos})

def produto_detalhes(request, slug):
    produto = get_object_or_404(Produto, slug=slug)
    return render(request, 'main/produto_detail.html', {'produto':produto})
'''
@login_required
def index(request):
    #form = Funcionario.objects.get(id=4)
    return render(request, 'main/index.html')

@login_required
def conferencia_list(request):
    conferencias = Conferencia.objects.all()
    filtro = ConferenciaFilter(request.GET, queryset = conferencias)
    conferencias = filtro.qs
    return render(request, 'main/conferencia_list.html', {'conferencias': conferencias, 'filtro': filtro})

'''
@login_required
def produto_list(requsest, codigo_barras):
    produtos = Produto.objects.all()
    filtro = ProdutoFilter(request.GET, queryset = produtos)
    produtos = filtro.qs

    return render(request, 'main/produto_list.html', {'Produtos': produtos, 'filtro': filtro})
'''

@login_required
def detalhes_conferencia(request, id):
    # conferencia = get_object_or_404(Validade_Produto, id=id)
    produtos_conferencia = Validade_Produto.objects.filter(conferencia_id = id).order_by('codigo_barras')
    print("detalhes_conferencia")
    return render(request, 'main/conferencia_detail.html', {'produtos_conferencia':produtos_conferencia})

@login_required
def nova_conferencia(request):
    print("nova_conferencia")         
    formulario_conferencia = ConferenciaForm()
    print(request.method)

    if request.method == 'POST':
        print("if")
        formulario_conferencia = ConferenciaForm(request.POST)

        if(formulario_conferencia.is_valid()):
            print("válido")
            nova_conferencia = formulario_conferencia.save(commit=False)
            func_id = request.user.id
            funcionario = Funcionario.objects.get(usuario_id = func_id)
            corredor_conferencia = formulario_conferencia.cleaned_data['corredor']
            
            nova_conferencia = Conferencia(corredor = corredor_conferencia, funcionario=funcionario)
            nova_conferencia.save()
            
            id_conferencia = nova_conferencia.id

            print('func: ',func_id)
            print('corredor: ',corredor_conferencia)  
            context = {'id_conf': id_conferencia}
            print(context)
            # print(reverse('detalhes_conferencia', id_conferencia))
            #else:
                #print(formulario_validade_produtos.errors)

            # return redirect(reverse('detalhes_conferencia', id_conferencia))
            # return redirect('/conferencias/'+str(id_conferencia)) # redirecionar para a página de adição de itens
            return redirect('/nova-conferencia-itens/') # redirecionar para a página de adição de itens

    elif(request.method == 'GET'):
        formulario_conferencia = ConferenciaForm()    
        
        # Se for um get, redireciona pra página de nova conferência
    return render(request, 'main/nova_conferencia.html', {'form': formulario_conferencia})

def nova_conferecia_itens(request):
    form = ValidadeProdutoForm()

    if request.method == 'POST':
        print('método post')
        formulario_validade_produtos = ConferenciaForm(request.POST) 
        
        if (formulario_validade_produtos.is_valid()):
            codigo_barras = formulario_validade_produtos.cleaned_data['data_barras']
            data_validade = formulario_validade_produtos.cleaned_data['data_validade']
            quantidade = formulario_validade_produtos.cleaned_data['validade']

            produto = Validade_Produto(
                codigo_barras=codigo_barras, 
                conferencia=id_conferencias, 
                data_validade=data_validade, 
                quantidade=quantidade)     

            return render(request, 'main/nova_conferencia_itens.html', {'form': formulario_validade_produtos})

    elif request.method == 'GET':
        form = ValidadeProdutoForm()
    
    return render(request, 'main/nova_conferencia_itens.html', {'form': form})


def busca_produto(request, codigo_barras):
    produto = Produto.objects.get(codigo_barras=codigo_barras)

    

'''
            print(formulario_validade_produtos['codigo_barras'].value())
            campo_codigo = formulario_validade_produtos['codigo_barras'].value()

            try:
                produto = Produto.objects.get(codigo_barras='7894561230')
            except Produto.DoesNotExist:
                raise ValidationError("Produto não encontrado")
'''

'''
            codigo = produto
            data_validade = formulario_validade_produtos.cleaned_data['data_validade']
            quantidade = formulario_validade_produtos.cleaned_data['quantidade'] 

            print(codigo)
            print(data_validade)
            print(quantidade)

            produto = Validade_Produto(codigo_barras=codigo, conferencia=nova_conferencia, data_validade=data_validade, quantidade=quantidade)
            produto.save()  
'''

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <title>{% block title %} {% endblock %} </title>
</head>
<body>
    {% if user.is_authenticated %}

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Validade Mercale</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">>         

            <ul class="navbar nav">
                <li> 
                    <a class="nav-item nav-link active" href="{% url 'main:index' %}">Home <span class="sr-only">(current)</span></a> 
                </li>
                
                <li>
                    <a class="nav-item nav-link active" href="{% url 'main:nova_conferencia' %}">Nova Conferência</a>
                </li>

                <li>
                    <a class="nav-item nav-link active" href="{% url 'main:lista_conferencia' %}">Conferências</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Relatórios
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="#">A vencer em 15 dias</a>
                      <a class="dropdown-item" href="#">A vencer em 30 dias</a>
                      <a class="dropdown-item" href="#">A vencer acima de 30 dias</a>
                    </div>
                  </li>
                
                <li>
                    <a class="nav-item nav-link" href="/accounts/logout">Sair</a>
                </li>
            </ul>
        </div>
      </nav>
    
    {% endif %}   
    
    <main>
        {% block content%}

        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/conferencia_detail.html
{% extends 'main/base.html' %}

{% block title %} Produtos Conferidos {% endblock %}

{% block content %} 

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Produto</th>
            <th scope="col">Vencimento</th>
            <th scope="col">Quantidade</th>
        </tr>
        </thead>

    {% for p in produtos_conferencia %}

            <tbody>
            <tr>
                <td scope="col"> {{ p.codigo_barras }} </a></td>
                <td scope="col">{{ p.data_validade }}</td>
                <td scope="col">{{ p.quantidade }}<td>
            </tr>
            </tbody>
        
        
    {% endfor %}

    </table>

{% endblock %}

main/templates/main/conferencia_list.html
{% extends 'main/base.html' %}

{% block title %} Conferências {% endblock title %}

{% block content %}

<form method="GET">

    {{ filtro.form }}

    <input type="submit" value="Buscar">

</form>


<table class="table table-striped table-hover" >
    <thead>
      <tr>
        <th scope="col">Local</th>
        <th scope="col">Funcionário</th>
        <th scope="col">Data</th>
      </tr>
    </thead>

    {% for c in conferencias %}
        
            <tbody>
                    <tr>
                        <td scope="col"> <a href="{{ c.get_absolute_url }}">{{ c.corredor.slug }} </a></td>
                        <td scope="col">{{ c.funcionario }}</td>
                        <td scope="col">{{ c.data_conferencia }}<td>
                    </tr>                          
            </tbody>
          
    {% endfor %}

    </table>
{% endblock content %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
    <h3>Bem-vindo ao sistema de controle de validade!</h3>

{% endblock content %}

main/templates/main/nova_conferencia.html
{% extends 'main/base.html' %}

{% load bootstrap %}

{% block title %} Nova Conferência {% endblock title %}

{% block content %}

<div class="container">
    <div class="col-4">
        <form action="" method="POST">
            {% csrf_token %}
                {{ form|bootstrap }}
            
            <input type="submit" value="Avançar">

        </form>
    </div>
</div>
{% endblock content %}

main/templates/main/nova_conferencia_itens.html
{% extends 'main/base.html' %}

{% load bootstrap %}

{% block title %} Nova conferência {% endblock %}

{%block content %} 
<div class="container">
    <div class="col-4">
        <form action="" method="POST">
            {% csrf_token %}
                {{ form|bootstrap }}
            
            <input type="submit" value="Avançar">

        </form>
    </div>
</div>

{% endblock %}

main/templates/main/produto_detail.html
{% extends 'main/base.html' %}

{% block title %} {{ produto.descricao }} {% endblock title %}

{% block content %}
    <h2> Descricão: {{ produto.descricao }}</h2>
    <p>  Código: {{ produto.codigo }}
    <br> 
    Código de barras: {{ produto.codigo_barras }}
    <br>
    Preço de venda: R$ {{ produto.preco_venda }}
    <br>
    Categoria: {{ produto.categoria }}
    </p>
{% endblock content %}

main/templates/main/produto_list.html
{% extends 'main/base.html' %}

{% block title %} Produtos {% endblock %}

{% block content %} 
    {% for p in produtos %}

    <article> 
        <h1> <a href="{{ p.get_absolute_url }}" > {{ p.descricao }}</a> </h1>
        <p> Código: {{ p.codigo }} </p>
        <p> Preço de venda: R$ {{ p.preco_venda }}</p>
        <p>Código de barras: {{ p.codigo_barras }}</p>   
        <p>Categoria: {{ p.categoria }}</p>

    </article>
    <!--Mostra as 10 primeiras palavras da descrição-->
    <!--{{ p.descricao|linebreaks|truncatewords:10 }}  -->
    
    {% endfor %}

{% endblock %}